### PR TITLE
Use full path for url in gitmodules

### PR DESCRIPTION
**Pull request by N00byKing**
Recursive clone fails on forks due to this. Use a full path instead to avoid this issue

### CODE REVIEW

**Comment by Antidote** [comment]
No, we have them relative for a reason.

**Comment by N00byKing** [comment]
oh ok. Out of interest, why do they need to be relative?

**Comment by Jcw87** [comment]
I assume that it is because these repositories are synced with gitlab, and they want clones from github to get everything from github, and clones from gitlab to get everything from gitlab.

**Comment by N00byKing** [comment]
Ah yeah, makes sense

**Pull request closed without merging**
